namespace GameWebsite.Models
{
    /// <summary>
    /// Represents a generic item in the game, serving as the base class for specific item types such as weapons or potions.
    /// </summary>
    public abstract class Item
    {
        /// <summary>
        /// The name of the item.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description of the item, detailing its properties or use.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// A unique identifier for the item, generated by replacing spaces in the name with underscores.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        /// <param name="name">The name of the item.</param>
        /// <param name="description">The description of the item.</param>
        public Item(string name, string description)
        {
            // Generate a unique ID by replacing spaces in the name with underscores
            Id = name.Replace(" ", "_");
            Name = name;
            Description = description;
        }
    }
}
